### ISSUE TITLE
"Class 'WebP\Convert' not found" error after uploading images

### ISSUE THREAD

**Issue by dviate** [felixhaeberle/kirby3-webp#1] opened 2020-06-05 14:35 UTC
Whenever I upload a file (see simple screencast in gif below), I keep receiving the "Class 'WebP\Convert' not found" error. The files I try to upload are uploaded in their original extension but not converted to .webp. 

![Hashtag #fail](https://dviate.net/webp.gif)

My installation went like this:
1. Downloaded zip-file from the master
2. Unzipped file to `development/clients/clientname/httpdocs/site/plugins/kirby3-webp/`
3. Copy/pasted stuff from the `.htaccess` sample to my `.htaccess`-file
4. Added the extra lines to `config.php`

But, whenever I look at the [composer.json](https://github.com/felixhaeberle/kirby3-webp/blob/master/composer.json)-file on line 6, I see `"rosell-dk/webp-convert": "^2.3"` which I didn't see in my installation list as mentioned above.

Did I do something wrong, or is the readme incomplete? 🤔

**Comment by felixhaeberle** [comment] 2020-06-05 19:35
Hey, thanks for reaching out, I think there is a bug in the Class Loading with missing dependencies. Will look into it tomorrow. 👋

**Comment by dviate** [comment] 2020-06-16 11:55
Did you find a solution, @felixhaeberle? :)

**Comment by felixhaeberle** [comment] 2020-06-18 23:57
Hey, sorry for not replying, fix is in the works. 👍 Will push tomorrow 🙏

**Comment by felixhaeberle** [comment] 2020-06-20 15:02
@dviate I push a fix to it this evening! 🤟

**Comment by felixhaeberle** [comment] 2020-06-22 08:40
@dviate Can you try again? I just pushed a new fix to the main branch. Sometimes, if the pictures are really big (multiple MB's) the converting process takes naturally longer, but does complete for sure. The *.webp gets generated, but not selected, because if the client can accept *.webp, the *.webp is sent to the client instead of the *.png or *.jpg. Because of the Apache/nginx configuration.

**Comment by jensschnitzler** [comment] 2020-06-26 09:00
Hello everyone and thank you for this plugin! 

I just installed the latest version of the plugin and I think I might be experiencing a related issue:

- after uploading an image in the panel, the following alert occurs: "source file was not found"
<img width="1273" alt="Bildschirmfoto 2020-06-26 um 10 57 54" src="https://user-images.githubusercontent.com/14975858/85839933-f49d8800-b79b-11ea-9983-3358d79e2ceb.png">

- in the respective content folder, no webp image is to be found
<img width="231" alt="Bildschirmfoto 2020-06-26 um 10 45 27" src="https://user-images.githubusercontent.com/14975858/85839930-f36c5b00-b79b-11ea-9523-3eb8eb58110c.png">

**Comment by timothyachumba** [comment] 2020-06-28 20:51
I seem to be facing the same issue as @jensschnitzler.

**Comment by felixhaeberle** [comment] 2020-06-30 10:12
Will look into it! Can you possibly attach the uploaded placeholder.png here?

**Comment by jensschnitzler** [comment] 2020-06-30 10:35
Thank you! 
Sure, it's just a random image i have on my desktop and regularly use for testing:

![placeholder](https://user-images.githubusercontent.com/14975858/86116658-16657a80-bace-11ea-967c-d55a6c6fdf6f.png)

**Comment by chrtz** [comment] 2020-07-04 09:05
@felixhaeberle FYI, I'm facing the same issue @jensschnitzler, too.

**Comment by felixhaeberle** [comment] 2020-07-07 07:39
@chrtz Okay, looking into it today! Also, I kindly appreciate any pull request or contribution. :)

**Comment by chrtz** [comment] 2020-07-07 08:26
@felixhaeberle sure, I'd like to help. But I might not be experienced enough.

I noticed, that I also just downloaded the zip, as @dviate did, too. @jensschnitzler did you also just downloaded the zip, or did you install the plug-in via composer/git submodule?

**Comment by Jonatanceja** [comment] 2020-07-08 18:11
> @felixhaeberle sure, I'd like to help. But I might not be experienced enough.
> 
> I noticed, that I also just downloaded the zip, as @dviate did, too. @jensschnitzler did you also just downloaded the zip, or did you install the plug-in via composer/git submodule?

Have the same issue, i just installed trough git submodule and composer. Both ways and have the same error.

**Comment by jensschnitzler** [comment] 2020-07-10 15:58
@chrtz i downloaded the zip :-)

**Comment by dviate** [comment] 2020-07-15 20:33
Sorry for the delay, I was offline for a few weeks ⛺️

I just followed the steps for the manual installation and I see the same error message as @chrtz and @jensschnitzler.

By the way, when I run `$ composer require felixhaeberle/kirby3-webp` I'm receiving the following error. I'm afraid that's caused by the fact that you didn't [tag](https://github.com/felixhaeberle/kirby3-webp/tags) this repo yet.

> [InvalidArgumentException]
  Could not find a version of package felixhaeberle/kirby3-webp matching your
   minimum-stability (stable). Require it with an explicit version constraint
   allowing its desired stability.

**Comment by felixhaeberle** [comment] 2020-07-17 15:35
Good news, this weekend I'll have some time to work on this issue :)
Thanks for the feedback and the bug descriptions! 👍

**Comment by rcvd** [comment] 2020-07-27 09:20
> Good news, this weekend I'll have some time to work on this issue :)
> Thanks for the feedback and the bug descriptions! 👍

Any news on this?

**Comment by casderooij** [comment] 2020-08-02 17:55
Hello everybody! This issue appears to be caused by the use of listed pages. I committed a [pull request](https://github.com/felixhaeberle/kirby3-webp/pull/2) 🙂

**Comment by felixhaeberle** [comment] 2020-08-02 18:38
@all Did the change fix your problem?

**Comment by rcvd** [comment] 2020-08-03 08:28
@felixhaeberle it works for me, thank you.

**Comment by dviate** [comment] 2020-08-03 21:27
@casderooij, great job! For me it works like a charm now. Can you tag this version for those who play around with Composer, @felixhaeberle? 🙏🏽

**Comment by felixhaeberle** [comment] 2020-08-06 17:43
I'll tag this version soon! Closing this by now.

**Closed as completed** 2020-08-09 21:08 UTC
